texts = {
  "en": {
      "configuration": "Configuration",
      "camera": "Camera",
      "page": "Page",
      "language": "Language",
      "show-about": "Show about button",
      "close": "Close",
      "apply": "Apply",
      "about": "About Piollo",
      "about-text": "by Eliot Blanco Lebrero.",
      "github": "View on GitHub",
      "img-format": "Format",
      "image-width": "Width",
      "image-height": "Height",
      "rotate-image": "Rotate",
      "flip-image": "Flip",
      "image-brightness": "Brightness",
      "image-contrast": "Contrast",
      "image-saturation": "Saturation",
      "image-sharpness": "Sharpness",
      "image-effect": "Effect",
      "none": "none",
      "negative": "negative",
      "solarize": "solarize",
      "sketch": "sketch",
      "denoise": "noise reduction",
      "emboss": "emboss",
      "oilpaint": "oil paint",
      "gpen": "gpen",
      "hatch": "hatch",
      "pastel": "pastel",
      "watercolor": "watercolor",
      "film": "film",
      "blur": "blur",
      "saturation": "saturation",
      "colorswap": "color swap",
      "washedout": "washed out",
      "posterise": "posterise",
      "colorpoint": "highlight color",
      "colorbalance": "colorbalance",
      "cartoon": "cartoon",
      "deinterlace1": "deinterlace1",
      "deinterlace2": "deinterlace2",
      "config-applied-success": "Configuration applied successfully",
      "kernel-size": "Kernel size",
      "enable-params": "Enable filter parameters",
      "strength": "Strength",
      "uv-offset": "UV offset"
  },
  "es": {
      "configuration": "Configuración",
      "camera": "Cámara",
      "page": "Página",
      "language": "Idioma",
      "show-about": "Mostrar el botón de información",
      "close": "Cerrar",
      "apply": "Aplicar",
      "about": "Acerca de Piollo",
      "about-text": "por Eliot Blanco Lebrero.",
      "github": "Ver en GitHub",
      "img-format": "Formato",
      "image-width": "Ancho",
      "image-height": "Altura",
      "rotate-image": "Rotar",
      "flip-image": "Voltear",
      "image-brightness": "Brillo",
      "image-contrast": "Contraste",
      "image-saturation": "Saturación",
      "image-sharpness": "Nitidez",
      "image-effect": "Efecto",
      "none": "ninguno",
      "negative": "negativo",
      "solarize": "solarizar",
      "sketch": "boceto",
      "denoise": "reducción de ruido",
      "emboss": "grabado",
      "oilpaint": "óleo",
      "gpen": "gpen",
      "hatch": "trazos",
      "pastel": "pastel",
      "watercolor": "acuarela",
      "film": "película",
      "blur": "desenfoque",
      "saturation": "saturación",
      "colorswap": "intercambio de colores",
      "washedout": "difuminado",
      "posterise": "posterizar",
      "colorpoint": "realzar color",
      "colorbalance": "colorbalance",
      "cartoon": "cartoon",
      "deinterlace1": "deinterlace1",
      "deinterlace2": "deinterlace2",
      "config-applied-success": "Configuración aplicada con éxito",
      "kernel-size": "Tamaño del kernel",
      "enable-params": "Habilitar parámetros del filtro",
      "strength": "Fuerza",
      "uv-offset": "Compensación UV"
  }
}